[phases.setup]
nixPkgs = ["dotnet-sdk_8", "icu"]

[phases.build]
cmds = [
  "dotnet publish Signalko.Web/Signalko.Web.csproj -c Release -o /app/publish"
]

[start]
cmd = "dotnet /app/publish/Signalko.Web.dll"
