// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Signalko.Infrastructure;

#nullable disable

namespace Signalko.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260311140000_AddPermissions")]
    partial class AddPermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Signalko.Core.Antenna", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<int>("ReaderId")
                        .HasColumnType("int");

                    b.Property<int>("RoleID")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("ReaderId");

                    b.HasIndex("RoleID");

                    b.HasIndex("ZoneId");

                    b.ToTable("antennas");
                });

            modelBuilder.Entity("Signalko.Core.AntennaRole", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Signalko.Core.Asset", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasColumnType("longtext");

                    b.Property<string>("Icon")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int?>("TagId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TagId");

                    b.ToTable("ASSET");
                });

            modelBuilder.Entity("Signalko.Core.AssetLoan", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LoanedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("AssetId");

                    b.HasIndex("UserId");

                    b.HasIndex("ZoneId");

                    b.ToTable("assets_loans");
                });

            modelBuilder.Entity("Signalko.Core.Permission", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));
                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");
                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");
                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");
                    b.HasKey("id");
                    b.HasIndex("Code").IsUnique();
                    b.ToTable("permissions");
                });

            modelBuilder.Entity("Signalko.Core.RolePermission", b =>
                {
                    b.Property<int>("RoleId").HasColumnType("int");
                    b.Property<int>("PermissionId").HasColumnType("int");
                    b.HasKey("RoleId", "PermissionId");
                    b.HasIndex("PermissionId");
                    b.ToTable("role_permissions");
                });

            modelBuilder.Entity("Signalko.Core.Author", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Author");
                });

            modelBuilder.Entity("Signalko.Core.ExchangeRequest", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("FromUserId")
                        .HasColumnType("int")
                        .HasColumnName("from_user_id");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Message");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("responded_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Status");

                    b.Property<int>("ToUserId")
                        .HasColumnType("int")
                        .HasColumnName("to_user_id");

                    b.HasKey("id");

                    b.HasIndex("AssetId");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.ToTable("exchange_requests");
                });

            modelBuilder.Entity("Signalko.Core.Reader", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Hostname")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IP")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("readers");
                });

            modelBuilder.Entity("Signalko.Core.Tag", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Antenna")
                        .HasColumnType("int");

                    b.Property<string>("Epc")
                        .HasColumnType("longtext");

                    b.Property<string>("EpcAscii")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Hostname")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("RSSI")
                        .HasColumnType("int");

                    b.Property<string>("ReaderIP")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<int?>("SEEN_COUNT")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("TAG");
                });

            modelBuilder.Entity("Signalko.Core.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("CardEpc")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("CardID")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(190)
                        .HasColumnType("varchar(190)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("longtext");

                    b.Property<int?>("ValidationId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("CardID")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("ValidationId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Signalko.Core.UserPresence", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("AntennaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("AntennaId");

                    b.HasIndex("ZoneId");

                    b.HasIndex("UserId", "ScannedAt");

                    b.ToTable("user_presence");
                });

            modelBuilder.Entity("Signalko.Core.UserRole", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Signalko.Core.Validation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Validation");
                });

            modelBuilder.Entity("Signalko.Core.Zone", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("zones");
                });

            modelBuilder.Entity("Signalko.Core.Antenna", b =>
                {
                    b.HasOne("Signalko.Core.Reader", "Reader")
                        .WithMany("Antennas")
                        .HasForeignKey("ReaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Signalko.Core.AntennaRole", "Role")
                        .WithMany("Antennas")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Signalko.Core.Zone", "Zone")
                        .WithMany("Antennas")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reader");

                    b.Navigation("Role");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Signalko.Core.Asset", b =>
                {
                    b.HasOne("Signalko.Core.Author", "Author")
                        .WithMany("Assets")
                        .HasForeignKey("AuthorId");

                    b.HasOne("Signalko.Core.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId");

                    b.Navigation("Author");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Signalko.Core.AssetLoan", b =>
                {
                    b.HasOne("Signalko.Core.Asset", "Asset")
                        .WithMany("Loans")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Signalko.Core.User", "User")
                        .WithMany("Loans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Signalko.Core.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId");

                    b.Navigation("Asset");

                    b.Navigation("User");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Signalko.Core.ExchangeRequest", b =>
                {
                    b.HasOne("Signalko.Core.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Signalko.Core.User", "User")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Signalko.Core.User", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("User");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("Signalko.Core.User", b =>
                {
                    b.HasOne("Signalko.Core.UserRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.HasOne("Signalko.Core.Validation", "Validation")
                        .WithMany()
                        .HasForeignKey("ValidationId");

                    b.Navigation("Role");

                    b.Navigation("Validation");
                });

            modelBuilder.Entity("Signalko.Core.UserPresence", b =>
                {
                    b.HasOne("Signalko.Core.Antenna", "Antenna")
                        .WithMany()
                        .HasForeignKey("AntennaId");

                    b.HasOne("Signalko.Core.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Signalko.Core.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId");

                    b.Navigation("Antenna");

                    b.Navigation("User");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Signalko.Core.RolePermission", b =>
                {
                    b.HasOne("Signalko.Core.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("Signalko.Core.UserRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Permission");
                    b.Navigation("Role");
                });

            modelBuilder.Entity("Signalko.Core.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Signalko.Core.AntennaRole", b =>
                {
                    b.Navigation("Antennas");
                });

            modelBuilder.Entity("Signalko.Core.Asset", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("Signalko.Core.Author", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("Signalko.Core.Reader", b =>
                {
                    b.Navigation("Antennas");
                });

            modelBuilder.Entity("Signalko.Core.User", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("Signalko.Core.UserRole", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Signalko.Core.Zone", b =>
                {
                    b.Navigation("Antennas");
                });
#pragma warning restore 612, 618
        }
    }
}
